### ISSUE TITLE
Does this code have predicted codon sequence output?

### ISSUE THREAD

**Issue by mintuos** [minotm/NTA#1]
Hello respected author, I tried your code but it did not output the optimized codon or amino acid sequence. Is this normal?

**Comment by minotm** [comment]
Dear mintuos, 

Thanks for your inquiry. The purpose of this repo is data augmentation to improve supervised machine learning workflows for predicting protein function from sequence. The repo does not seek to optimize amino acid or nucleotide sequences. However, a variety of these tools can be found on the web. For example:

https://www.ebi.ac.uk/Tools/st/emboss_backtranseq/
https://www.nature.com/articles/s41598-020-74091-z
https://eu.idtdna.com/pages/tools/codon-optimization-tool
